---
- name: Update auto.master for autofs
  ansible.builtin.lineinfile:
    path: /etc/auto.master
    state: present
    line: '/mnt /etc/auto.nfs --ghost --timeout=60'

- name: Create auto.nfs
  ansible.builtin.lineinfile:
    path: /etc/auto.nfs
    state: present
    create: true
    line: 'storage -fstype=nfs4,rw 192.168.1.169:/srv/storage'

- name: Restart service autofs, in all cases
  ansible.builtin.service:
    name: autofs
    state: restarted
