---
- name: "Remove profile file"
  hosts:
    - rpis
    - proxmox_all_lxc:!mealie:!ntfy
  become: true
  tasks:
    - name: "Remove /etc/profile.d/00_lxc-details.sh if it exists"
      ansible.builtin.file:
        path: "/etc/profile.d/00_lxc-details.sh"
        state: absent
