$ANSIBLE_VAULT;1.1;AES256
35643636366436333966336431613965306664346664303639666536626332316235633433333938
3762333064656161306563373264336262343439386664350a633365386362336366393433646536
39663764323064343330613866316330623464366337313030346430346134303439313330326533
6538393335383664660a383631623739363736613161386430323062666663303763666461636531
39623963336364353834373664636336383966386233353737646163616462323530643231656339
62353366666134306162303465363936363132666136643463386661316333313131643734376536
36656133626465643732353731653161303338616534666264633832323634633337356430323735
62313639316635633535393034643765306534316462303138343732343838646661313230393139
33656261303037303232353936636330653038353537323933383538323562613866663330376663
61336234633938393666386563656364343861343437373765653733663532663262326436316132
64343033366333653238373264653337353338366366333530313263333330653565396262303033
63303663353561333939386233333461643464646437343564623361616165343766386565636134
63366134316339346236363531633833306337363366316433376561633934643337323638623432
64363032353163363835623536313866633239313363616464633638353734643066366531303533
61323837366566306534303934636136643230663835316362356164623633303939396632346234
36373864333563613864633133356164313937363833396235613364326233663139666531356164
33343763363433353362333336306362376637623031383966303233616534633930646535643636
3766386337643534373031323037363839393763653537623239
