$ANSIBLE_VAULT;1.1;AES256
61336131393738623234643038393264353366623831656139383533633937386462396430383466
6463396331613165316636343461346338353561303165350a333535323566366437656438346234
61636664313165656130356231663730653666313661316136306332316565346131393332363934
3263623537373861360a323063313263643037383363643837353466333637343136373664333035
39626336663233356633613361633937326561393638393366373034383437396336653433666561
34616331663839396664373138393261626133613365653663623464653739303237646565613637
35646632636565303964363031313662636337643365363134356463346331343065393030633730
34653339633937666163623132376632346265323137663463376364396638326133346636383832
32666333393138313132333031646638653932616363363236303131356632386537326230323463
33363439346164386232636631656133646239633135373134663937663230626630623633393831
37373830323939356333383164643932613564316638656337333831366464343736303564316239
35643133363065353534303833326365653238636639623932633665323232373363383438363031
37336335633431623332383730616231336231626139306230313962356534613038626136346436
30333766666134396165376465663330363761643430393633343761636434623134343438393764
31356237343766623430303732366637313436366439363333323336613330306664376634646635
31306463393061316531613030316431396534343239656236663066383135633836303061636562
31303135373434366331393832366531613434666463383130383435326536343430393434363637
6234353733643539313338633366653265336231336635613630
